import { Product } from "./types";

const data:Product[] = [
  {
    id: 0,
    name: 'Rose',
    image: '/catalog/rose.jpg',
    type: 'Крем',
    shortDesc: 'Крем для лица',
    longDesc: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется        по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток. ',
    composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода. ',
    volume: ['80ml', '30ml'],
    cost: '656'
  },
  {
    id: 1,
    name: 'Rose',
    image: '/catalog/rose.jpg',
    type: 'Крем',
    shortDesc: 'Крем для лица',
    longDesc: 'Увлажняющий крем идеально подходит для повседневного ухода за молодой кожей. Крем равномерно распределяется        по поверхности благодаря легкой текстуре, обеспечивает глубокое увлажнение, регенерацию клеток. ',
    composition: 'Aqua, Cyclomethicone, Dicaprylyl Carbonate, Butylene Glycol, Glycerin, Tapioca Starch, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Нанесите крем на очищенную кожу лица легкими массажными круговыми движениями, избегая области вокруг глаз. Подходит для дневного и ночного ухода. ',
    volume: ['80ml', '30ml'],
    cost: '890'
  },
  {
    id: 2,
    name: 'High',
    image: '/catalog/high.jpg',
    type: 'Крем',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores eligendi sed ipsa magnam aperiam repudiandae repellat iure nisi ad sunt.',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml', '30ml', '999ml'],
    cost: '666'
  },
  {
    id: 3,
    name: 'Rest',
    image: '/catalog/rest.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['69ml'],
    cost: '777'
  },
  {
    id: 4,
    name: 'Rose',
    image: '/catalog/rose.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 5,
    name: 'Milk',
    image: '/catalog/milk.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml', '66ml'],
    cost: '777'
  },
  {
    id: 6,
    name: 'Paradise',
    image: '/catalog/paradise.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['666ml'],
    cost: '777'
  },
  {
    id: 7,
    name: 'Sun',
    image: '/catalog/sun.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['88ml'],
    cost: '777'
  },
  {
    id: 8,
    name: 'Violet',
    image: '/catalog/violet.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 9,
    name: 'Clean',
    image: '/catalog/clean.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '999'
  },
  {
    id: 10,
    name: 'Coconut',
    image: '/catalog/coconut.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '180'
  },
  {
    id: 11,
    name: 'Lavender',
    image: '/catalog/lavender.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '1337'
  },
  {
    id: 12,
    name: 'Lotos',
    image: '/catalog/lotos.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 13,
    name: 'Earth',
    image: '/catalog/earth.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 14,
    name: 'Earth',
    image: '/catalog/earth.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 15,
    name: 'Earth',
    image: '/catalog/earth.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 16,
    name: 'Clean',
    image: '/catalog/clean.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '999'
  },
  {
    id: 17,
    name: 'Coconut',
    image: '/catalog/coconut.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '180'
  },
  {
    id: 18,
    name: 'Lavender',
    image: '/catalog/lavender.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '1337'
  },
  {
    id: 19,
    name: 'Lotos',
    image: '/catalog/lotos.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 20,
    name: 'Earth',
    image: '/catalog/earth.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 21,
    name: 'Earth',
    image: '/catalog/earth.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 22,
    name: 'Earth',
    image: '/catalog/earth.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 23,
    name: 'Earth',
    image: '/catalog/earth.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 24,
    name: 'Earth',
    image: '/catalog/earth.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
  {
    id: 25,
    name: 'Earth',
    image: '/catalog/earth.jpg',
    type: 'Сыворотка',
    shortDesc: 'Lorem ipsum dolor sit amet.',
    longDesc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis, distinctio, nisi nostrum eligendi laboriosam tempore facilis voluptates nesciunt laborum inventore assumenda fugit magnam architecto?',
    composition: 'Aqua, Nelumbium Speciosum Flower Extract, Calendula Officinalis Flower Extract, Propylene Glycol, Tocopherol, Glycine Soja Oil, Dimethiconol, Citronellol, Limonene.',
    application: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, incidunt quasi! Tenetur expedita minima fuga.',
    volume: ['50ml'],
    cost: '777'
  },
]

export default data;